version: 2

project_name: simdiag

before:
  hooks:
    - go mod tidy
    - goimports -w .
    - go fmt ./...
    - golangci-lint run

builds:
  - id: simdiag-windows
    main: ./cmd/simdiag
    binary: simdiag
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.simdiagVersion={{ .Version }}

archives:
  - id: windows-archive
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"
    files:
      - templates/*.svg

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

