package gui

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

// The Tips tab is documentation the interface carries itself, so that SimDiag can
// be used without reading the README. Two of its offers need Go: writing a batch
// script the user can double-click, and opening a web page outside the webview.

const (
	batchScriptName = "run_simdiag_batch.bat"

	// batchScriptMarker tells a script SimDiag wrote from one the user wrote by
	// hand. The name has been in circulation long before this button existed (a
	// two-line run_simdiag_batch.bat sits in most installs), and overwriting
	// someone's own flags without asking would be rude.
	batchScriptMarker = "REM Generated by SimDiag"
)

// externalLinks is the whole set of pages the interface offers to open, and by
// being a fixed table it is also the allow list: the frontend names a
// destination, never a URL. The webview is a browser, and handler.go is
// deliberately paranoid about what it will act on.
var externalLinks = map[string]string{
	"drawio":        "https://www.drawio.com/",
	"openkneeboard": "https://openkneeboard.com/",

	"github":         "https://github.com/yesnault/simdiag",
	"githubReleases": "https://github.com/yesnault/simdiag/releases",
	"githubIssues":   "https://github.com/yesnault/simdiag/issues",
	"license":        "https://github.com/yesnault/simdiag/blob/master/LICENSE",
}

// releaseLink is the one destination whose address is not known in advance: it
// changes with every version. Go still resolves it, so the rule the table exists
// for holds: the page names a destination, it never carries a URL.
var releaseLink struct {
	sync.Mutex
	url string
}

func rememberReleaseLink(url string) {
	releaseLink.Lock()
	defer releaseLink.Unlock()
	releaseLink.url = url
}

// linkURL resolves a destination the page named.
func linkURL(target string) (string, bool) {
	if target == "release" {
		releaseLink.Lock()
		defer releaseLink.Unlock()
		return releaseLink.url, releaseLink.url != ""
	}

	url, known := externalLinks[target]
	return url, known
}

type batchScriptRequest struct {
	Overwrite bool `json:"overwrite"`
}

// batchScriptResponse reports what happened. A file already there that SimDiag
// did not write is not a failure but a question, and comes back as a plain
// answer the frontend turns into a confirmation rather than as an error.
type batchScriptResponse struct {
	Created bool   `json:"created"`
	Exists  bool   `json:"exists"`
	Path    string `json:"path"`
}

type openURLRequest struct {
	Target string `json:"target"`
}

func registerTipsRoutes(mux *http.ServeMux, state *State) {
	mux.HandleFunc("POST /api/tips/batch-file", func(w http.ResponseWriter, r *http.Request) {
		var req batchScriptRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
			http.Error(w, "invalid request: "+err.Error(), http.StatusBadRequest)
			return
		}

		configPath, err := filepath.Abs(state.ConfigPath())
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		script := filepath.Join(batchScriptDirectory(configPath), batchScriptName)

		if !req.Overwrite && fileExists(script) && !isGeneratedBatchScript(script) {
			writeJSON(w, batchScriptResponse{Exists: true, Path: script})
			return
		}

		content, err := batchScriptContent(configPath)
		if err != nil {
			writeMessageError(w, http.StatusInternalServerError, msgBatchScriptFailed, errorArg(err))
			return
		}
		if err := os.WriteFile(script, []byte(content), 0644); err != nil {
			writeMessageError(w, http.StatusInternalServerError, msgBatchScriptFailed, errorArg(err))
			return
		}

		// Showing it is the point: the user is meant to double-click it next.
		if err := revealFile(script); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		writeJSON(w, batchScriptResponse{Created: true, Path: script})
	})

	mux.HandleFunc("POST /api/open-url", func(w http.ResponseWriter, r *http.Request) {
		var req openURLRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "invalid request: "+err.Error(), http.StatusBadRequest)
			return
		}

		url, known := linkURL(req.Target)
		if !known {
			http.Error(w, "unknown link: "+req.Target, http.StatusBadRequest)
			return
		}

		if err := openExternalURL(url); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		writeJSON(w, map[string]bool{"opened": true})
	})
}

// batchScriptDirectory decides where the script goes: next to the executable,
// which is where a user looks for it. If that directory is read-only (an
// install under Program Files) it joins the configuration instead.
func batchScriptDirectory(configPath string) string {
	if dir := exeDir(); dir != "" && dirWritable(dir) {
		return dir
	}
	return filepath.Dir(configPath)
}

// isGeneratedBatchScript reports whether the file at path is one of ours.
func isGeneratedBatchScript(path string) bool {
	data, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(data), batchScriptMarker)
}

// batchScriptContent builds the script.
//
// The cd is the load-bearing line, not the -c. Configurations name their
// templates and output relatively to themselves (output_directory: output) and
// the CLI never chdirs. It resolves those against the working directory, which
// for a double-clicked .bat is the directory the .bat sits in. Without the cd the
// export would run to completion and quietly write its diagrams beside the
// script instead of into the configured output directory.
//
// The rest: the executable is named absolutely because after the cd a bare
// simdiag.exe is no longer resolvable and the binary is not on PATH; chcp 65001
// because the pipeline prints check marks and accented action names that the
// stock OEM codepage mangles; and pause because the console window would
// otherwise close on the last line. The output shows up at all thanks to
// app.AttachParentConsole. The binary is linked -H windowsgui and is handed no
// standard handles of its own.
func batchScriptContent(configPath string) (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("unable to locate simdiag.exe: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}

	lines := []string{
		"@echo off",
		batchScriptMarker + " - regenerates every diagram without opening the interface.",
		"chcp 65001 >nul",
		"cd /d " + quoted(filepath.Dir(configPath)),
		quoted(exe) + " -b -c " + quoted(configPath),
		"echo.",
		"pause",
		"",
	}

	// CRLF: cmd.exe is the one reader of this file and it has never been happy
	// with bare newlines.
	return strings.Join(lines, "\r\n"), nil
}

// quoted wraps a path for cmd.exe. Deliberately not %q, which is Go quoting: it
// would double every backslash in a Windows path and escape the accents a user
// name can carry.
func quoted(path string) string {
	return `"` + path + `"`
}

// revealFile shows the generated script to the user. It is a variable so the
// tests can exercise the route without Explorer windows opening on the machine
// running them.
var revealFile = openInFileManager

// openExternalURL hands a web page to the system browser.
//
// A plain <a href> would navigate the application window itself: the webview is
// a browser showing the interface at "/", and there is no way back from it.
func openExternalURL(url string) error {
	switch runtime.GOOS {
	case "windows":
		// rundll32 rather than cmd /c start, which would flash a console
		// window on a binary linked as -H windowsgui.
		return exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Run()
	case "darwin":
		return exec.Command("open", url).Run()
	default:
		return exec.Command("xdg-open", url).Run()
	}
}
